url: "https://mrinalcs.github.io"
title: "Mrinal Chandra Sarkar"

author:
  name: Mrinal Chandra Sarkar
  url: https://mrinalcs.github.io

twitter:
  username: mrinalcs
  card: summary

webmaster_verifications:
  google: MqwDRSLNo0fmAemi7VVB_g6f7Z9KU9u_EhcaU9icYbQ

permalink: /:title
 
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-redirect-from 
  - jekyll-minifier


jekyll-minifier:
  exclude:
    - index.umd.js
    - Swup.umd.js


collections:
  pages:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      toc: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      seo:
        type: WebPage
        
exclude:
  - README.md