url: "https://mrinalcs.github.io"
title: "Mrinal Chandra Sarkar"
description: Mrinal's Github Page

lang: en-IN


nav:
  - title: About
    url: /
  - title: Blog
    url: /blog
  - title: Photos
    url: /photos

author:
  name: Mrinal Chandra Sarkar
  url: https://mrinalcs.github.io

social:
  name: Mrinal Chandra Sarkar
  links:
    - https://twitter.com/mrinalcs
    - https://www.facebook.com/mrinalcs
    - https://www.linkedin.com/in/mrinalcs
    - https://github.com/mrinalcs

twitter:
  username: mrinalcs
  card: summary

github:
  username: mrinalcs
  repo: mrinalcs.github.io

webmaster_verifications:
  google: MqwDRSLNo0fmAemi7VVB_g6f7Z9KU9u_EhcaU9icYbQ

gtag: G-SHN1H6Y4R5

permalink: /:title
 
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-redirect-from 

feed:
  disable_in_development: true
  
sass:
   sourcemap: development

collections:
  pages:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      render_with_liquid: false
      toc: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      seo:
        type: WebPage


comment-read: https://docs.google.com/spreadsheets/d/1hVRP9tYl8f4bsBjJP52hv74DwZ2pYpatxaNMG2rNY_M
comment-post: https://docs.google.com/forms/d/e/1FAIpQLSehE6misroMb1QUK57ReR8JeO_eVxztTlojKRcXCbWDwYtHTQ
comment-post-fields: [ entry.46315812, entry.361353560, entry.1184144290]


exclude:
  - README.md