url: "https://mrinalcs.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Mrinal Chandra Sarkar" # the name of your site, e.g. ACME Corp.
description: Mrinal's Github Page
permalink: /:title


plugins:
  - jekyll-remote-theme

remote_theme: mrinalcs/turbo-memory

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      render_with_liquid: false